spring:
  application:
    name: wallet
  profiles:
    default: dev

  data:
    jdbc:
      dialect: mysql

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate.format_sql: true
      envers:
        audit_table_suffix: _history

  messages:
    encoding: UTF-8

# Actuator configuration for monitoring and management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  #  server:
  #    port: 8086
  tracing:
    sampling:
      probability: '1.0'

# Logging configuration
logging:
  level:
    root: info

# Caffeine cache configuration
cache:
  short:
    ttl: '60'
  default:
    max-size: '1000'
  medium:
    ttl: '120'

# Custom app constants
constants:
  api-url: url
  api-key: key
  default-auditor: SYSTEM

app:
  jwt.secret-key: ${APP_JWT_SECRET_KEY}
  jwt.validity-in-minutes: 60

encryption:
  secret: ${APP_ENC_SECRET}

