spring:
  jpa:
    show-sql: false

logging:
  level:
    com.gucardev: info
    org.hibernate.SQL: info
    org.springframework.web: info
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR

springdoc:
  swagger-ui:
    enabled: false

